# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e90d071b8768424586550e572482cba203734d10455d47d3d202ae73cb7c6547908e8aed3baafee6af1887e8a877d3d57f31df3064f2e8ddb601cd2b8456e3d8

test:
  secret_key_base: 976165af9210e00ec50831da24146d7a29219ad1902f986d7e1db56b5c6b986e09211f538d8f5bdb247f5d5cad7ff5c5a765d7246b1ab39e1f5ec41c639e7a41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
